### ISSUE TITLE
STAC: Add 'url' for the processing software

### ISSUE THREAD

**Issue by l0b0** [linz/stac#152]
@billgeo commented on [Mon Nov 01 2021](https://github.com/linz/ds-infra-team/issues/839)

### User Story

So that we can easily find the software that created a dataset we would like software URL for the 'processing software' in addition to the software name and software version.

### Additional information
The [processing extension](https://github.com/stac-extensions/processing) currently has a string that can contain dictionary of values for software name and version.

See discussion on Slack here: https://linz.slack.com/archives/CN7F6HP2Q/p1635731683032700

### Tasks
- [ ] Design some implementation options
- [ ] Draft one or more PRs with schema and documentation changes
- [ ] Test options with LINZ users

---

@l0b0 commented on [Tue Nov 09 2021](https://github.com/linz/ds-infra-team/issues/839#issuecomment-963754441)

This is [already supported by the processing schema](https://github.com/stac-extensions/processing/blob/b47551ef1125beeefb39e9b6fbc78e8f2dd07532/json-schema/schema.json#L248-L260) - you can literally put any string property inside `processing:software`. `name`/`version` are just suggestions, not actually required (or even named) by the schema.

**Comment by l0b0** [comment]
Blocked by https://github.com/stac-extensions/processing/pull/6 and https://github.com/stac-extensions/processing/pull/9.

**Comment by billgeo** [comment]
Looks like those two blockers may have been resolved by https://github.com/stac-extensions/processing/pull/18 ? Are you to confirm this or establish if this is still blocked @l0b0 ?
